services:
  postgres:
    image: postgres:16-alpine
    container_name: hsin-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hsin
      POSTGRES_PASSWORD: hsin_dev
      POSTGRES_DB: hsin_db
    ports:
      - "5432:5432"
    volumes:
      - hsin_pgdata:/var/lib/postgresql/data

volumes:
  hsin_pgdata:
